### PR TITLE
Add an integration test and a bare-bone Matter controller

### PR DESCRIPTION
**Pull request by mfucci**
This also introduces a skeleton for the Matter client

### CODE REVIEW

**Review by jottinger — APPROVED** [review]

**Review by jdesai61 — COMMENTED** [review]
How can I test the controller - can you please put in some lines in README o such? Thanks

**Comment by mfucci** [comment]
Done!

You can also test the controller in the integration test:
npm run test -- -g Integration

**Review by jottinger — APPROVED** [review]

**Review by jdesai61 — COMMENTED** [review]
Never mind. I was not using Node 16

**Review by jdesai61 — COMMENTED** [review]
Now the pairing between built-in test controller and node-matter works. However, with Home Assistant, I am getting following error

node build/Main.js -on "echo On" -off "echo Off"
Pase server: Received pairing request from udp://192.168.1.57:47322
Pase server: Paired succesfully with udp://192.168.1.57:47322
Received read request from udp://192.168.1.57:47322 on session secure/30993: */49/65532, 0/48/0, 0/48/1, 0/48/2, 0/48/3, 0/40/2, 0/40/4, */49/3
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/48/0
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/48/2
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/62/2
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/62/2
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/62/0
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/62/4
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/62/11
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/62/6
**Error: Missing mandatory field rcacId
    at Function.decodeObject (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:74:27)
    at Function.decodeInternal (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:57:29)**
    at Function.decodeObject (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:71:32)
    at Function.decodeInternal (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:57:29)
    at Function.decodeElement (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:24:21)
    at Function.decode (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:21:21)
    at FabricBuilder.setNewOpCert (/home/DadAdmin/node-matter/build/fabric/Fabric.js:69:83)
    at OperationalCredentialsCluster.<anonymous> (/home/DadAdmin/node-matter/build/interaction/cluster/OperationalCredentialsCluster.js:54:32)
    at Generator.next (<anonymous>)
    at /home/DadAdmin/node-matter/build/interaction/cluster/OperationalCredentialsCluster.js:8:71
Received invoke request from udp://192.168.1.57:47322 on session secure/30993: 0/48/0

**Comment by mfucci** [comment]
Node version: added a check so it should crash with an explicit message when the version is not supported

Missing mandatory field rcacId: I split the definition of the root cert and the operational cert. Apparently, the self-sign root cert doesn't not require to specify itself as the issuer. Updated the code to know issue root cert without issuer RcacId, so it should not be required anymore.

**Comment by jdesai61** [comment]
Now I am getting another missing field request (issuerRcacId)

Received invoke request from udp://192.168.1.57:56083 on session secure/31864: 0/62/6
Error: Missing mandatory field issuerRcacId
    at Function.decodeObject (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:74:27)
    at Function.decodeInternal (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:57:29)
    at Function.decodeObject (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:71:32)
    at Function.decodeInternal (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:57:29)
    at Function.decodeElement (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:24:21)
    at Function.decode (/home/DadAdmin/node-matter/build/codec/TlvObjectCodec.js:21:21)
    at FabricBuilder.setNewOpCert (/home/DadAdmin/node-matter/build/fabric/Fabric.js:69:83)
    at OperationalCredentialsCluster.<anonymous> (/home/DadAdmin/node-matter/build/interaction/cluster/OperationalCredentialsCluster.js:54:32)
    at Generator.next (<anonymous>)
    at /home/DadAdmin/node-matter/build/interaction/cluster/OperationalCredentialsCluster.js:8:71
Received invoke request from udp://192.168.1.57:56083 on session secure/31864: 0/48/0

**Comment by mfucci** [comment]
Hmmm... I guess that field is also optional in the Operational Certificate (NOC) in that case.

The certificate chain is supposed to be this one, so I guess this field is not really needed:
Root <- Root (root is self signed)
Root <- NOC
Root <- IntermediateCA <- NOC (if IntermediateCA is present)

I made it optional now. Can you check again?

**Comment by jdesai61** [comment]
It is much better now and device is showing up again in UI. However, even if I don't do anything - just wait for a few seconds, I get "CASE session resume not supported" messages.  The same errors also happen when I try to turn the switch on or off using Home Assistant UI. Attached HA log may give some clues
```
node build/Main.js -on "echo On" -off "echo Off"
[hamatter.log](https://github.com/mfucci/node-matter/files/9636734/hamatter.log)

Pase server: Received pairing request from udp://192.168.1.57:37951
Pase server: Paired succesfully with udp://192.168.1.57:37951
Received read request from udp://192.168.1.57:37951 on session secure/50898: */49/65532, 0/48/0, 0/48/1, 0/48/2, 0/48/3, 0/40/2, 0/40/4, */49/3
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/48/0
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/48/2
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/62/2
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/62/2
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/62/0
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/62/4
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/62/11
Received invoke request from udp://192.168.1.57:37951 on session secure/50898: 0/62/6
Case server: Received pairing request from udp://192.168.1.57:37951
Case server: Paired succesfully with udp://192.168.1.57:37951
Received invoke request from udp://192.168.1.57:37951 on session secure/50899: 0/48/4
Received read request from udp://192.168.1.57:37951 on session secure/50899: */*/*
Received subscribe request from udp://192.168.1.57:37951 on session secure/50899
Received read request from udp://192.168.1.57:37951 on session secure/50899: 1/6/0
Case server: Received pairing request from udp://192.168.1.57:37951
An error occured during the commissioning Error: CASE session resume not supported
    at CaseServer.<anonymous> (/home/DadAdmin/node-matter/build/session/secure/CaseServer.js:43:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/DadAdmin/node-matter/build/session/secure/CaseServer.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


Case server: Received pairing request from udp://192.168.1.57:37951
An error occured during the commissioning Error: CASE session resume not supported
    at CaseServer.<anonymous> (/home/DadAdmin/node-matter/build/session/secure/CaseServer.js:43:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/DadAdmin/node-matter/build/session/secure/CaseServer.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jdesai61** [comment]
Likely these messages from HA Log may help you find the problem
```
2022-09-23 15:38:50 77f1785d-matter-server chip.SC[122] ERROR Received error (protocol code 2) during pairing process: ../../src/protocols/secure_channel/CASESession.cpp:1605: CHIP Error 0x00000054: Invalid CASE parameter
2022-09-23 15:38:50 77f1785d-matter-server chip.DMG[122] ERROR Failed to establish CASE for re-subscription with error '../../src/protocols/secure_channel/CASESession.cpp:1605: CHIP Error 0x00000054: Invalid CASE parameter'
2022-09-23 15:38:50 77f1785d-matter-server chip.DMG[122] INFO Will try to resubscribe to 01:00000000000010EF at retry index 1 after 8686ms due to error ../../src/protocols/secure_channel/CASESession.cpp:1605: CHIP Error 0x00000054: Invalid CASE parameter
2022-09-23 15:38:50 77f1785d-matter-server chip.EM[122] INFO <<< [E:49369i M:27876012 (Ack:2240057831)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
2022-09-23 15:38:50 77f1785d-matter-server chip.IN[122] INFO (U) Sending msg 27876012 to IP address 'UDP:192.168.1.28%enp0s18:5540'
2022-09-23 15:38:58 77f1785d-matter-server chip.DMG[122] INFO OnResubscribeTimerCallback: DoCASE = 0
```

**Comment by jdesai61** [comment]
Apparently after about 35 seconds, HA thinks that liveliness timer has expired and tries to establish a new session...
```
2022-09-23 15:38:49 77f1785d-matter-server chip.DMG[122] ERROR Subscription Liveness timeout with SubscriptionID = 0x00000000, Peer = 01:00000000000010EF
2022-09-23 15:38:49 77f1785d-matter-server chip.SC[122] INFO SecureSession[0x7fc23801faa0]: Moving from state 'kActive' --> 'kDefunct'
2022-09-23 15:38:49 77f1785d-matter-server chip.DMG[122] INFO Will try to resubscribe to 01:00000000000010EF at retry index 0 after 0ms due to error ../../src/app/ReadClient.cpp:867: CHIP Error 0x00000032: Timeout
2022-09-23 15:38:49 77f1785d-matter-server chip.DMG[122] INFO OnResubscribeTimerCallback: DoCASE = 1
/usr/lib/python3.9/asyncio/events.py:80: RuntimeWarning: coroutine 'DefaultResubscriptionAttemptedCallback' was never awaited
  self._context.run(self._callback, *self._args)
```

**Comment by mfucci** [comment]
OK, thanks!

I think this should be an existing problem unrelated to this change:

- the subscription doesn't send a regular heartbeat (issue already filed part of https://github.com/mfucci/node-matter/issues/11 )
- after the connection drops, re-pairing fails because CASE session resume is not supported (issue already filed https://github.com/mfucci/node-matter/issues/28 )

I will go ahead and merge this change and fix subscription in follow PRs. I can now write integration tests, so this should speed up fixing issues.

**Review by javierbarellano4v — APPROVED** [review]

**Pull request merged**
