### PR TITLE
Revert incorrect change from admincomm-cluster-rework 

### PR DESCRIPTION
**Pull request by Apollon77**
which caused ios pairing issues. By reverting this pairing on ios work again - devices stil unresponsive for me, but pairing works

### CODE REVIEW

**Comment by Apollon77** [comment]
@mfucci verified, this restores iOS functionality ...

**Comment by vves** [comment]
I just validated that this update allows for the Matter Simulated Device to be added to the iOS Home App on iOS 16.3.  Home App still displays "No Response", but at least commissioning seems to be working again.

**Comment by Apollon77** [comment]
For no response: does it load when you tap the device in home app and make it "big"
In the App? 

Do you have an HomePod?

**Review by mfucci — APPROVED** [review]

**Comment by mfucci** [comment]
For Matter devices operations, Apple requires a Apple-compatible hub to be present on the local network, since operating the device is actually done through the cloud and not on the local network (the same for Google, a Google-compatible hub is require for operations).

**Pull request merged**
