### PR TITLE
Placeholder for subscribe

### PR DESCRIPTION
**Pull request by mfucci**
The method doesn't do anything but it should return a correct response

### CODE REVIEW

**Review by jdesai61 — COMMENTED** [review]
As a placeholder this works.  Will you open a new issue for real subscribe implementation? If so, we can close this one.

**Comment by mfucci** [comment]
This placeholder seems to have some bad side-effects if HA keeps trying to subscribe again... I will try to replace this placeholder with the real implementation in this PR.

**Comment by mfucci** [comment]
@jdesai61 Actually, can you approve this one so I can merge? The Descriptor branch has been merged into this branch instead of main so this is creating a mess...

In the future, can you just approve and not merge? I will ensure that it merges on the correct branch and delete the branch linked to the PR

**Review by jdesai61 — APPROVED** [review]
Approved - sorry for the delay

**Pull request merged**
