### PR TITLE
Execute CLA - Wes

### PR DESCRIPTION
**Pull request by vves**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hello @vves Signing the CLA is used if you weant to provide code to this library, so please bring in your first PR additionally and then we can also get you into your CLA, but a CLA without really providing also code makes not that much sense right now.

**Comment by vves** [comment]
@Apollon77 @mfucci looking forward to helping out.

**Comment by Apollon77** [comment]
Cool, Is there a topic you plan to start with?

**Comment by vves** [comment]
@Apollon77 two things:   1. I am starting on the  review of the bridge branch and 2. providing a fix for OSX usage of the library (ticket I just opened)

**Comment by vves** [comment]
I am focused on the Bridge code and adding Window Covering cluster.

**Comment by Apollon77** [comment]
@vves The bridge code will be replaced soon by a new "high level API" I wourk on right now ... so also the bridge PR will be killed and replaced y this new API. Hopefulyl I have something to review there in some days.

The clusters would be cool to add.

**Review by mfucci — APPROVED** [review]

**Comment by Apollon77** [comment]
I would leave thta here until we have the first real PR from @vves :-)

**Pull request merged**
