### PR TITLE
Test for renaming

### PR DESCRIPTION
**Pull request by mfucci**

### CODE REVIEW

**Comment by Apollon77** [comment]
Try now to change the cntent of the renamed file please ... lets see if this is then same issue as with me

**Comment by mfucci** [comment]
Now with content change in 2nd commit

**Comment by Apollon77** [comment]
grmppffff ... no idea why it behaved that way with my Webstorm :-( Ok ... as said ... I do rename in extra PR

**Comment by Apollon77** [comment]
Thank you for the test

**Pull request closed without merging**
