### PR TITLE
Add definitions and partial refactoring

### PR DESCRIPTION
**Pull request by mfucci**
Sorry not finished yet... I need to go to bed...

### CODE REVIEW

**Comment by Apollon77** [comment]
Alternative: leave the old types in and I do the cleanup in follow up pr and then we remove old types when done. Will not need long.

**Comment by Apollon77** [comment]
Would the "Bound" also work to e.g. limit a GroupId (aka 16 bit number 0..max) in some cases to 1..max? Because we need this in some places. If yes that would be awesome.

As said in other PRs: Make it easy and just use the new types in 1-2 places ... and leave old types in and I fix all of that (because if have that done all locally already - no need that you work through specs again - I did yesterday whole day kind of)

**Comment by mfucci** [comment]
Finished now! I had to finish the updating all the integer types to have it compiling.
I found some bugs as well that I fixed.

**Comment by Apollon77** [comment]
wow you are up early :-) Checking now ... will check then when merging my local stuff in (yeeayyy - that will be fun) ;-))

**Review by Apollon77 — DISMISSED** [review]
LGTM ... I will recheck all when merging with my local changes again

**Comment by mfucci** [comment]
I fixed UInt64 maximum. I took Int64 max instead of UInt64 and it crashed when I tried against iOs 16.1

**Review by Apollon77 — APPROVED** [review]

**Comment by Apollon77** [comment]
approved

**Comment by mfucci** [comment]
Sorry, after merging I need your Appoval stamp again before I can merge :-)

**Review by Apollon77 — APPROVED** [review]
sure, and here you go

**Pull request merged**
