### PR TITLE
Fix subscription

### PR DESCRIPTION
**Pull request by mfucci**
Add missing protocolVersion field

### CODE REVIEW

**Review by jdesai61 — APPROVED** [review]
While I am not able to do a full meaningful review of long list of code changes, I have tested this with HA and it seems to work - I don't see any error messages on HA or node-matter side and thus I am approving this PR.

**Comment by mfucci** [comment]
@Apollon77 Can you have a quick look at the code and approve? Jatin already tested to ensure that it works

**Comment by Apollon77** [comment]
on it

**Review by Apollon77 — APPROVED** [review]
without checking all details. code is fine

**Comment by Apollon77** [comment]
LGTM

**Pull request merged**
